apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: manuela-data-lake-factory-mirror-maker
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    #LRC repoURL: https://github.com/redhat-edge-computing/manuela-gitops.git
    repoURL: https://github.com/claudiol/manuela-gitops.git
    targetRevision: HEAD
    path: config/instances/manuela-data-lake/factory-mirror-maker
  destination:
    server: https://kubernetes.default.svc
    namespace: manuela-data-lake-factory-mirror-maker
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: apps
    kind: Deployment
    jsonPointers:
    - /spec/replicas
  - group: route.openshift.io
    kind: Route
    jsonPointers:
    - /status
  - group: image.openshift.io
    kind: ImageStream
    jsonPointers:
    - /spec/tags
  - group: apps.openshift.io
    kind: DeploymentConfig
    jsonPointers:
    - /spec/template/spec/containers/0/image
